donateReceive/Controllers/PostCommentController.cs
using donateReceive.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace donateReceive.Controllers
{
    [Authorize]
    public class PostCommentController : Controller
    {
        // GET: PostComment

        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {

            return View();
        }
        [Authorize]
        public ActionResult Comments(string _Id, string _postedBlood, string verb, string _distance)
        {
            if (_Id != null)
            {
                ApplicationUser user = db.Users.FirstOrDefault(e => e.Id == _Id);
                var base64 = Convert.ToBase64String(user.photo);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                PostCommentViewModel model = new PostCommentViewModel
                {
                    posterId = _Id,
                    posterName = user.UserName,
                    posterStatus = user.extraInfo,
                    posterBlood = _postedBlood,
                    posterDate = user.statusPostTime,
                    imgSrc = imgSrc,
                    verb = verb,
                    displayNumber = user.displayPhoneNumber,
                    number = user.PhoneNumber,
                    distance = _distance,



                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public void PostNotification(string id)
        {

            ApplicationUser user = db.Users.FirstOrDefault(e => e.Id == id);
            user.notification = true;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();

        }
    }
}

donateReceive/Views/PostComment/Comments.cshtml
@model donateReceive.Models.PostCommentViewModel
@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/_LayoutComments.cshtml";
}
<script>
    $("#fbdiv").attr("data-href", document.location.href);
</script>

@using (Html.BeginForm("Comments", "PostComment"))
{
    @Html.AntiForgeryToken()
    <div class="jumbotron" style="background-color:#eee">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="box box-success">
                        <div class="box-body chat" id="chat-box">

                            <div class="item">
                                <img src="@Model.imgSrc" alt="user image" class="online">
                                <p class="message" style="font-size:medium">
                                    <a class="name">

                                        @Model.posterName

                                        <small class="text-muted"><i class="fa fa-clock-o"></i>@Model.verb</small>
                                        @{
                                            string distance = "";
                                            if (Model.distance.IsEmpty() == false)
                                            {
                                                distance = Model.distance + "km";
                                            }
                                            else if (Model.distance.IsEmpty() == true)
                                            {
                                                distance = "";
                                            }
                                        }
                                        <small class="text-muted pull-right"><i class="fa fa-clock-o"></i>@distance</small>


                                        @Model.posterBlood
                                        @if (Model.displayNumber == true)
                                        {
                                            <small class="text-muted"> (@Model.number)</small>
                                        }
                                    </a>

                                    <small class="text-muted" style="font-size:x-small"><i class="fa fa-clock-o"></i> @Model.posterDate</small>

                                </p>
                                <p style="font-size:medium;word-wrap:break-word">  @Model.posterStatus </p>
                            </div>
                        </div>

                        @*</div>
                            </div>*@
                    </div>
                    <div id="fbdiv" class="fb-comments" data-href="" data-width="485" data-numposts="5"></div>

                </div>


            </div>
        </div>

    </div>

                                            }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}